package com.rs.game.player.content.interfaces.teleports;

import com.rs.game.WorldTile;

public class TeleportsData {

    /*
     *  CORP(8133,3,"MELEE, MAGE", "HARD", new WorldTile(2969,4383,2), false, 3500),
    KBD(50,1,"MELEE, MAGE", "EASY", new WorldTile(3053, 3519, 0), false, 3500),
    NEX(13450,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(2904, 5203, 0), false, 1800),
    AOD(24004,4,"MELEE, MAGE, RANGE", "HARD", new WorldTile(2904, 5199, 0), false, 1800),
    BORK(7134,3,"MELEE", "EASY", new WorldTile(3143, 5545, 0), false, 2200),
    KQUEEN(1160,3,"MELEE, RANGE", "EASY", new WorldTile(3479, 9488, 0), false, 2200),
    REX(2883,3,"MELEE", "EASY", new WorldTile(1912, 4367, 0), false, 2000), //maybe not here
    PRIME(2882,3,"MAGE", "EASY", new WorldTile(1912, 4367, 0), false, 2000), //maybe not here
    SUPREME(2881,3,"RANGE", "EASY", new WorldTile(1912, 4367, 0), false, 2000), //maybe not here
    BARREL(5666,3,"MELEE", "EASY", new WorldTile(3803, 2844, 0), false, 2200),
    SUNFREET(15222,3,"MELEE, MAGE", "HARD", new WorldTile(3179, 9766, 0), false, 2500),
    QBD(20551,3,"MELEE, RANGE", "MEDIUM", new WorldTile(1195, 6499, 0), true, 1000),
    KKING(16697,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(2974, 1654, 0), false, 3000),
    CHAOSELEMENTAL(3200,3,"MAGE, RANGE", "MEDIUM", new WorldTile(3141, 3814, 0), false, 1500),
    ARRAXOR(19463,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(3700, 3419, 0), true, 3500),
    //BARROWS(22738,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(3700, 3419, 0), true, 1100),
    //ROTS(22351,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(3700, 3419, 0), true, 500),
    VORAGO(17182,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(2972, 3430, 0), false, 3700),
    GWD(6260,1,"MELEE, MAGE, RANGE", "MEDIUM", new WorldTile(2916, 3739, 0), false, 3000),
    GWD2(22925,3,"MELEE, MAGE, RANGE", "HARD", new WorldTile(3372, 2882, 0), false, 800),
    HOPEDEV(12900,1,"MELEE, MAGE, RANGE", "HARD", new WorldTile(3291,3886,0), false, 2500),
    ZULRAH(26023,1,"MELEE, MAGE, RANGE", "HARD", new WorldTile(3244,3173,0), false, 3200),
    TDEAMON(8350,1,"RANGE", "EASY", new WorldTile(2573,5733,0), false, 2500);
     */
    
    // Max entries is 30 for each category
    public enum Store {
        //BOSSES
         BANDOS(0, new Teleport(0, new TeleportCategory(0, "Bosses"), "Bandos", new String[] {"6260","1","ALL STYLES","MEDIUM","3000"}, 0, new WorldTile(2868, 5354, 0), false, -1, 105,true)),
         ZAMORAK(0, new Teleport(1, new TeleportCategory(0, "Bosses"), "Zamorak", new String[] {"6203","1","ALL STYLES","MEDIUM","3000"}, 0, new WorldTile(2925, 5330, 0), false, -1, 105,true)),
         ARMADYL(0, new Teleport(2, new TeleportCategory(0, "Bosses"), "Armadyl", new String[] {"6222","1","ALL STYLES","MEDIUM","3000"}, 0, new WorldTile(2832, 5299, 0), false, -1, 105,true)),
         SARADOMIN(0, new Teleport(3, new TeleportCategory(0, "Bosses"), "Saradomin", new String[] {"6247","1","ALL STYLES","MEDIUM","3000"}, 0, new WorldTile(2922, 5251, 0), false, -1, 105,true)),
         BORK(0, new Teleport(4, new TeleportCategory(0, "Bosses"), "Bork", new String[] {"7134","3","MELEE","EASY","2200"}, 0, new WorldTile(3143, 5545, 0), false, -1, 105,false)),
         CORP(0, new Teleport(5, new TeleportCategory(0, "Bosses"), "Corporeal Beast", new String[] {"8133","2","MELEE, MAGE","HARD","3500"}, 0, new WorldTile(2969,4383,2), false, -1, 105,true)),
         KBD(0, new Teleport(6, new TeleportCategory(0, "Bosses"), "King Black Dragon", new String[] {"50","1","MELEE, MAGE","EASY","3500"}, 0, new WorldTile(3053, 3519, 0), false, -1, 105,true)),
         NEX(0, new Teleport(7, new TeleportCategory(0, "Bosses"), "Nex", new String[] {"13450","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(2904, 5203, 0), false, -1, 105,false)),
         AOD(0, new Teleport(8, new TeleportCategory(0, "Bosses"), "AOD", new String[] {"8596","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(1807,3212, 0), false, -1, 105,false)),
         GIANT_MOLE(0, new Teleport(9, new TeleportCategory(0, "Bosses"), "Giant Mole", new String[] {"3340","1","MELEE","EASY","1800"}, 0, new WorldTile(1761,5186,0), false, -1, 105,false)),
         ALCH_HYDRA(0, new Teleport(10, new TeleportCategory(0, "Bosses"), "Alchemical Hydra", new String[] {"39615","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(1353, 10258, 0), false, -1, 105,false)),
         N_WILDY_WYRM(0, new Teleport(11, new TeleportCategory(0, "Bosses"), "Normal WildyWyrm", new String[] {"3334","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(3202, 3876, 0), true, 45, 105,false)),
         H_WILDY_WYRM(0, new Teleport(12, new TeleportCategory(0, "Bosses"), "Hardmode WildyWyrm", new String[] {"30025","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(2994,3890, 0), true, 46, 105,false)),
         A_WILDY_WYRM(0, new Teleport(13, new TeleportCategory(0, "Bosses"), "Aquatic WildyWyrm", new String[] {"30085","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(3062,3809,0), true, 37, 105,false)),
         //TRIO(0, new Teleport(14, new TeleportCategory(0, "Bosses"), "Demi God Trio", new String[] {"30065","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(2630, 5059, 0), false, -1, 105,false)),
         VORAGO(0, new Teleport(14, new TeleportCategory(0, "Bosses"), "Vorago", new String[] {"30009","3","ALL STYLES","VERY HARD","1800"}, 0, new WorldTile(3450, 9522, 0), false, -1, 105,false)),
         VORKATH(0, new Teleport(15, new TeleportCategory(0, "Bosses"), "Vorkath", new String[] {"39061","3","ALL STYLES","HARD","1800"}, 100000, new WorldTile(1807,3212, 0), false, -1, 105,false)),
         NIGHT_GAZER(0, new Teleport(16, new TeleportCategory(0, "Bosses"), "Night Gazer", new String[] {"9752","1","MAGE,RANGE","MEDIUM","1800"}, 0, new WorldTile(2413,3529, 0), false, -1, 105,false)),
         //BAD_SANTA(0, new Teleport(17, new TeleportCategory(0, "Bosses"), "Bad Santa", new String[] {"1552","1","MAGE","MEDIUM","1800"}, 0, new WorldTile(2648, 10425, 0), false, -1, 105,false)),
         KK(0, new Teleport(17, new TeleportCategory(0, "Bosses"), "Kalphite King", new String[] {"29993","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(3362, 2791, 0), false, -1, 105,false)),
         //HOPE_DEVOURER(0, new Teleport(19, new TeleportCategory(0, "Bosses"), "Hope Devourer", new String[] {"12900","3","ALL STYLES","VERY HARD","1800"}, 0, new WorldTile(2260,3602, 0), false, -1, 105,false)),
         DAGANNOTH_LAIR(0, new Teleport(18, new TeleportCategory(0, "Bosses"), "Dagannoth Lair", new String[] {"2883","2","ALL STYLES","MEDIUM","1800"}, 0, new WorldTile(2905,4453, 0), false, -1, 105,false)),
         ZULRAH(0, new Teleport(19, new TeleportCategory(0, "Bosses"), "Zulrah", new String[] {"16387","3","ALL STYLES","MEDIUM","1800"}, 0, new WorldTile(3249,9867, 0), false, -1, 105,false)),
         ROTS(0, new Teleport(20, new TeleportCategory(0, "Bosses"), "Rise of the Six", new String[] {"16387","3","ALL STYLES","MEDIUM","1800"}, 0, new WorldTile(3249,9867, 0), false, -1, 105,false)),
         //NECROLORD(0, new Teleport(23, new TeleportCategory(0, "Bosses"), "Necrolord", new String[] {"11751","3","RANGE,MAGIC","HARD","1800"}, 0, new WorldTile(3812,3060, 0), false, -1, 105,false)),
         //THUNDEROUS(0, new Teleport(24, new TeleportCategory(0, "Bosses"), "Yk'lagor the Thunderous", new String[] {"11872","3","MELEE,MAGIC","MEDIUM","1800"}, 0, new WorldTile(2574,9500, 0), false, -1, 105,false)),
         SUNFREET(0, new Teleport(21, new TeleportCategory(0, "Bosses"), "Sunfreet", new String[] {"15222","3","ALL STYLES","HARD","1800"}, 0, new WorldTile(2983,3958, 0), true, 55, 105,false)),
         ANIVIA(0, new Teleport(22, new TeleportCategory(0, "Bosses"), "Anivia", new String[] {"30081","3","MELEE,MAGIC","HARD","1800"}, 0, new WorldTile(2788,3788, 0), false, -1, 105,false)),
         SLISKE(0, new Teleport(23, new TeleportCategory(0, "Bosses"), "Sliske", new String[] {"14262","3","ALL STYLES","VERY HARD","1800"}, 0, new WorldTile(3365,3887, 0), true, 46, 105,false)),
         KQ(0, new Teleport(24, new TeleportCategory(0, "Bosses"), "Kalphite Queen", new String[] {"1158","1","RANGE,MAGIC","EASY","1800"}, 0, new WorldTile(3508,9493, 0), false, -1, 105,false)),
         KRAKEN(0, new Teleport(25, new TeleportCategory(0, "Bosses"), "Kraken", new String[] {"16385","1","MAGIC","MEDIUM","1800"}, 0, new WorldTile(3694,5803, 0), false, -1, 105,false)),
         ABYSSAL_SIRE(0, new Teleport(26, new TeleportCategory(0, "Bosses"), "Abyssal Sire", new String[] {"36886","1","MELEE","MEDIUM","1800"}, 0, new WorldTile(3694,5803, 0), false, -1, 105,false)),
         CERBERUS(0, new Teleport(27, new TeleportCategory(0, "Bosses"), "Cerberus", new String[] {"36862","1","ALL STYLES","MEDIUM","1800"}, 0, new WorldTile(1240, 1229, 0), false, -1, 105,false)),
         SIRENIC(0, new Teleport(28, new TeleportCategory(0, "Bosses"), "Sirenic", new String[] {"30008","1","MAGIC","MEDIUM","1800"}, 0, new WorldTile(3335, 3894, 0), true, 46, 105,false)),
         CALLISTO(0, new Teleport(29, new TeleportCategory(0, "Bosses"), "Callisto", new String[] {"37503","1","MELEE,MAGIC","MEDIUM","1800"}, 0, new WorldTile(3298, 3846, 0), true,41, 105,false)),
         VENENATIS(0, new Teleport(30, new TeleportCategory(0, "Bosses"), "Venenatis", new String[] {"37504","1","MELEE,MAGIC","MEDIUM","1800"}, 0, new WorldTile(3353, 3757, 0), true, 30, 105,false)),
         CHAOS(0, new Teleport(31, new TeleportCategory(0, "Bosses"), "Chaos Fanatic", new String[] {"37619","1","MAGIC","MEDIUM","1800"}, 0, new WorldTile(2979, 3850, 0), true, 42, 105,false)),
         ARCHEOLOGIST(0, new Teleport(32, new TeleportCategory(0, "Bosses"), "Crazy Archeologist", new String[] {"37618","1","MAGIC","MEDIUM","1800"}, 0, new WorldTile(2975, 3697, 0), true, 23, 105,false)),
         SCORPIA(0, new Teleport(33, new TeleportCategory(0, "Bosses"), "Scorpia", new String[] {"37615","1","MELEE","MEDIUM","1800"}, 0, new WorldTile(3245, 10349, 0), true, 54, 105,false)),
         VETION(0, new Teleport(34, new TeleportCategory(0, "Bosses"), "Vet'ion", new String[] {"37611","1","MELEE,MAGIC","MEDIUM","1800"}, 0, new WorldTile(3253, 3807, 0), true, 36, 105,false)),
         TD(0, new Teleport(35, new TeleportCategory(0, "Bosses"), "Tormented Demons", new String[] {"8349","1","ALL STYLES","MEDIUM","1800"}, 0, new WorldTile(2562, 5739, 0), false, -1, 105,false)),
         //BUNNY(0, new Teleport(41, new TeleportCategory(0, "Bosses"), "Angry Bunny", new String[] {"29975","1","ALL STYLES","MEDIUM","1800"}, 0, new WorldTile(3179, 9766, 0), false, -1, 105,false)),
         //AMIGOS(0, new Teleport(42, new TeleportCategory(0, "Bosses"), "The 3 Amigos", new String[] {"11983","1","ALL STYLES","HARD","1800"}, 0, new WorldTile(584, 4552, 0), false, -1, 105,false)),
         QBD(0, new Teleport(36, new TeleportCategory(0, "Bosses"), "Queen Black Dragon", new String[] {"15454","1","ALL STYLES","HARD","1800"}, 0, new WorldTile(1197, 6501, 0), false, -1, 105,false)),
        
         
         //MONSTERS
         COWS(5, new Teleport(0, new TeleportCategory(1, "Monsters"), "Cows", new String[] {"12362","1","MELEE","EASY","1500"}, 0, new WorldTile(3257, 3286, 0), false, -1, 3,false)),   
         ROCK_CRABS(5, new Teleport(1, new TeleportCategory(1, "Monsters"), "Rock Crabs", new String[] {"1265","1","MELEE","EASY","1500"}, 0, new WorldTile(2674, 3710, 0), false, -1, 3,false)),
         NOOB_OF_ZAMORAK(5, new Teleport(2, new TeleportCategory(1, "Monsters"), "Noob of Zamorak", new String[] {"453","1","MELEE","EASY","1500"}, 0, new WorldTile(2896, 2728, 0), false, -1, 3,false)),   
         HILL_GIANTS(5, new Teleport(3, new TeleportCategory(1, "Monsters"), "Hill Giant", new String[] {"117","1","MELEE","EASY","1500"}, 0, new WorldTile(3117,9852, 0), false, -1, 3,false)),   
         GREEN_DRAGS(5, new Teleport(4, new TeleportCategory(1, "Monsters"), "Green Dragons", new String[] {"941","1","MELEE, RANGE","EASY","1500"}, 0, new WorldTile(2984,3596, 0), true, 10, 80,false)),   
       
        
        //RAIDS
        LAIR_OF_SHADOWS(9, new Teleport(0, new TeleportCategory(2, "Raids"), "Lair of Shadows", new String[] {"Rumor has ir demons want to take over Hydrix with their almighty power!<br>You'll have to survive walls of fire, explosions, falling rocks, dodge bombs and<br>that's just the beginning of the challenges you'll face in the lair of shadows!<br>Grab your sword and shield and prepare for the most challeging adventure you have ever been on in the world of hydrix!"}, 0, new WorldTile(2856, 2592, 0), false, -1, 138,false)),       
        COX(9, new Teleport(1, new TeleportCategory(2, "Raids"), "Chambers of Xeric", new String[] {"Defeat your way through the chambers with a maximum of 5 people and encounter a luminescent icefiend, vyrewatch, pit rock protector and tekton in your way to obtain a reward chest!"}, 1000000, new WorldTile(3257, 3286, 0), false, -1, 138,false)),       
        TOB(9, new Teleport(2, new TeleportCategory(2, "Raids"), "Theatre of Blood", new String[] {"Slay the four bosses, ramokee stormbringer, justiciar, Troll ranger and finally the hardest boss of them all the blood beast with your team to obtain a reward chest!"}, 2000000, new WorldTile(3257, 3286, 0), false, -1, 138,false)),
        HYBRID_TRIO(9, new Teleport(3, new TeleportCategory(2, "Raids"), "Hybrid Trio", new String[] {"Annihilate the trio, vanguard, trickster and battle-mage with your team of 3 and have a slim chance of earning a part of their armour!"}, 0, new WorldTile(2403, 2841, 0), false, -1, 138,false)),
        GULEGA(9, new Teleport(4, new TeleportCategory(2, "Raids"), "Gulega", new String[] {"A dungeoneering type raid where you have to mine, smith, fish, cook everything youself before you try and kill the Gulega boss!"}, 0, new WorldTile(2403, 2841, 0), false, -1, 138,false)),
        
        //MINIGAMES
        DUEL_ARENA(10, new Teleport(0, new TeleportCategory(3, "Minigames"), "Duel Arena", new String[] {"A place where players can go to engange in one-on-one combat, either for fun or for staking coins/items."}, 0, new WorldTile(3365, 3266, 0), false, -1, -1,false)),
        //THE_CALAMITY(10, new Teleport(1, new TeleportCategory(3, "Minigames"), "The Calamity", new String[] {"A minigame where you kill several NPCs to earn points to spend on armour, weapons, food and potions."}, 0, new WorldTile(2832, 3858, 0), false, -1, -1,false)),
        CLAN_WARS(10, new Teleport(1, new TeleportCategory(3, "Minigames"), "Clan Wars", new String[] {"A place for players to engage in player-versus-player combat against one another"}, 0, new WorldTile(2992, 9678, 0), false, -1, -1,false)),
        //HEIST(10, new Teleport(3, new TeleportCategory(3, "Minigames"), "Heist", new String[] {"Heist is a minigame which involves two opposing teams. <br> Try to secure loot undetected while the other team attempt to kill the robbers, secure the loot before time runs out."}, 0, new WorldTile(3506, 3313, 0), false, -1, -1,false)),
        TEMPLE_OF_LIGHT(10, new Teleport(2, new TeleportCategory(3, "Minigames"), "Temple Of Light", new String[] {"Kill Mummies, touch pillars to obtain caskets for some amazing loot!"}, 0, new WorldTile(2438, 3315, 0), false, -1, -1,false)),
        SLAYER_SURVIVAL(10, new Teleport(3, new TeleportCategory(3, "Minigames"), "Slayer Survival", new String[] {"A minigame where you kill several slayers NPCs (51 total waves),<br> finish the waves to obtain points to spend in the Slayer Survival Rewards Shop."}, 0, new WorldTile(3430, 3522, 0), false, -1, -1,false)),
        WARRIORS_GUILD(10, new Teleport(4, new TeleportCategory(3, "Minigames"), "Warriors Guild", new String[] {"Kill Cyclops for a chance to get a brand new defender!"}, 0, new WorldTile(2871, 3542, 0), false, -1, -1,false)),
        DOMINION_TOWER(10, new Teleport(5, new TeleportCategory(3, "Minigames"), "Dominion Tower", new String[] {"The Dominion Tower houses a minigame which gives players the opportunity to re-fight various bosses."}, 0, new WorldTile(3361, 3082, 0), false, -1, -1,false)),
        FIGHT_KILN(10, new Teleport(6, new TeleportCategory(3, "Minigames"), "Fight Kiln", new String[] {"The Fight Kiln is a combat minigame wherein waves of TokHaar are fought. It's a tougher and improved sequel to the TzHaar Fight Cave minigame."}, 0, new WorldTile(4744, 5172, 0), false, -1, -1,false)),
        FIGHT_CAVES(10, new Teleport(7, new TeleportCategory(3, "Minigames"), "Fight Caves", new String[] {"The TzHaar Fight Cave is a combat minigame it involves single-handedly fighting off 63 waves of TzHaar creatures!<br> After completing the fight caves for the first time you'll only have to deal with Jad!"}, 0, new WorldTile(4610, 5130, 0), false, -1, -1,false)),
        FIGHT_PITS(10, new Teleport(8, new TeleportCategory(3, "Minigames"), "Fight Pits", new String[] {"The TzHaar Fight Pit is a PVP minigame located in TzHaar City, in which a group of players compete to be the last one standing"}, 0, new WorldTile(4600, 5062, 0), false, -1, -1,false)),
        CASTLE_WARS(10, new Teleport(9, new TeleportCategory(3, "Minigames"), "Castle Wars", new String[] {" Castle Wars is a minigame, It is similar to Capture the Flag"}, 0, new WorldTile(2442, 3090, 0), false, -1, -1,false)),
        //PLAYER_WARS(10, new Teleport(12, new TeleportCategory(3, "Minigames"), "Player Wars", new String[] {"A minigame where you have to defeat some old school hydrix players, you get player wars point when you complete this minigame which you can spend at the player wars store."}, 0, new WorldTile(3222, 3425, 0), false, -1, -1,false)),
        //TRIAL_OF_THE_GODS(10, new Teleport(13, new TeleportCategory(3, "Minigames"), "Trial Of The Gods", new String[] {"A mini game where you kill medium difficulty bosses and other monsters around Harmony!<br><br>Information:<br>You get ascension coins as a reward, you'll need 250,000 coins and a chaotic crossbow to create an ascension crossbow!"}, 0, new WorldTile(3244, 3197, 0), false, -1, -1,false)),
        BARROWS(10, new Teleport(10, new TeleportCategory(3, "Minigames"), "Barrows", new String[] {""}, 0, new WorldTile(3566, 3297, 0), false, -1, -1,false)),

        
      
        //SKILLING
        SKILLING(11, new Teleport(0, new TeleportCategory(4, "Skilling"), "Skilling Areas", new String[] {"Please select which skill you wish to train."}, 0, null, false, -1, -1,false)),       
            SKILLER_ISLAND(11, new Teleport(0, new TeleportCategory(6, "Skilling"), "Skiller Island", new String[] {"A special place where you can Woodcut Normal trees all the way to Magic Trees, <br> Mine and smith ores all the way to runite ores! <br> Hunt red chinchompas and Grenwalls <br>Fish and Cook all the way to Sharks! "}, 0, new WorldTile(3808, 3569, 0), false, -1, -1,false)),
            WILD_SKILL_ISLAND(11, new Teleport(1, new TeleportCategory(6, "Skilling"), "Wilderness Skilling ", new String[] {"A dangerous place in deep wilderness where you can mine Ancient ores, Adamantite ores and Runite ores! <br> Woodcut maple and magic trees and fish rocktails! <br> You will obtain X2 Skilling points while in this area."}, 0, new WorldTile(3186, 3933, 0), true, 52, -1,false)),
        WC(12, new Teleport(1, new TeleportCategory(4, "Skilling"), "Woodcutting", new String[] {"Select an area you would like to train Woodcutting."}, 0, null, false, -1, -1,false)),
            WC_AREA(12, new Teleport(0, new TeleportCategory(6, "Skilling"), "Woodcutting Area", new String[] {"A place to cut normal trees all the way to magic trees with a bank near by!"}, 0, new WorldTile(2725,3491, 0), false, -1, 3,false)),
            WC_GUILD(12, new Teleport(1, new TeleportCategory(6, "Skilling"), "Woodcutting Guild", new String[] {"A place to cut yew trees, magic trees and the big redwood tree!"}, 0, new WorldTile(1588, 3488, 0), false, -1, 3,false)),
        DUNG(13, new Teleport(2, new TeleportCategory(4, "Skilling"), "Dungeoneering", new String[] {"Select an area you would like to train Dungeoneering."}, 0, null, false, -1, -1,false)),
            LOW(13, new Teleport(0, new TeleportCategory(6, "Skilling"), "Low(1-50)", new String[] {"An easy level cave to train up your dungeoneering from level 1 to level 50! <br>Take your own gear/weapons and items!"}, 0, new WorldTile(3476, 9705, 0), false, -1, 3,false)),
            MEDIUM(13, new Teleport(1, new TeleportCategory(6, "Skilling"), "Medium(51-95)", new String[] {"A medium level cave to train up your dungeoneering from level 51 to level 95! <br>Take your own gear/weapons and items!"}, 0, new WorldTile(3478, 9845, 0), false, -1, 3,false)),
            HIGH(13, new Teleport(2, new TeleportCategory(6, "Skilling"), "High(96-120)", new String[] {"A high level cave to train up your dungeoneering from level 96 to level 120! <br>Do you have what it takes to slay this final boss?<br>Take your own gear/weapons and items!"}, 0, new WorldTile(2838, 10104, 0), false, -1, 3,false)),
        FARMING(14, new Teleport(3, new TeleportCategory(4, "Skilling"), "Farming", new String[] {"Select an area you would like to train Farming."}, 0, null, false, -1, -1,false)),
            TAV(14, new Teleport(0, new TeleportCategory(6, "Skilling"), "Taverly", new String[] {"A teleport to a tree patch."}, 0, new WorldTile(2923, 3430, 0), false, -1, -1,false)),
            FAL(14, new Teleport(1, new TeleportCategory(6, "Skilling"), "Falador", new String[] {"A teleport to a tree patch."}, 0, new WorldTile(3004,3377, 0), false, -1, 3,false)),
            LUM(14, new Teleport(2, new TeleportCategory(6, "Skilling"), "Lumbridge", new String[] {"A teleport to a tree patch."}, 0, new WorldTile(3195, 3234, 0), false, -1, 3,false)),
            VAR(14, new Teleport(3, new TeleportCategory(6, "Skilling"), "Varrock", new String[] {"A teleport to a tree patch."}, 0, new WorldTile(3224,3454, 0), false, -1, 3,false)),
            GNOME(14, new Teleport(4, new TeleportCategory(6, "Skilling"), "Gnome", new String[] {"A teleport to a tree patch. <br> TIP: teleport to Gnome Agility course for an easy fruit tree patch."}, 0, new WorldTile(2435, 3427, 0), false, -1, 3,false)),
            BRIMHAVEN(14, new Teleport(5, new TeleportCategory(6, "Skilling"), "Brimhaven", new String[] {"A teleport to a fruit tree patch."}, 0, new WorldTile(2768,3215, 0), false, -1, 3,false)),
            CATH(14, new Teleport(6, new TeleportCategory(6, "Skilling"), "Catherby", new String[] {"A teleport to a flower, herb and two allotment patches! <br> Run south then east after the bank to get to a fruit tree patch."}, 0, new WorldTile(2807, 3464, 0), false, -1, 3,false)),
            CAN(14, new Teleport(7, new TeleportCategory(6, "Skilling"), "Canifis", new String[] {"A spooky teleport to a flower, herb and two allotment patches!"}, 0, new WorldTile(3604,3529, 0), false, -1, 3,false)),
            DRAY(14, new Teleport(8, new TeleportCategory(6, "Skilling"), "Draynor", new String[] {"A teleport to a flower, herb and two allotment patches!"}, 0, new WorldTile(3053,   3306, 0), false, -1, 3,false)),
            ARDOUGNEFARM(14, new Teleport(9, new TeleportCategory(6, "Skilling"), "Ardougne", new String[] {"A teleport to a flower, herb and two allotment patches!"}, 0, new WorldTile(2663,  3375, 0), false, -1, 3,false)),
        SLAYER(15, new Teleport(4, new TeleportCategory(4, "Skilling"), "Slayer", new String[] {"Select an area you would like to train Slayer."}, 0, null, false, -1, -1,false)),       
            SLAYER_TOWER(15, new Teleport(0, new TeleportCategory(6, "Skilling"), "Slayer Tower", new String[] {"A quick teleport to the Slayer Tower where you can find:<br>Ground floor: Crawling hands, Jellies, Dust Devils and Banshees.<br>First Floor: Aberrant spectres, Infernal mages and Bloodvelds.<br>Second floor: Dark beasts, Gargoyles, Nechryaels and Abyssal demons."}, 0, new WorldTile(3423, 3544, 0), false, -1, 3,false)),
            GANODERMIC_BEAST(15, new Teleport(1, new TeleportCategory(6, "Skilling"), "Ganodermic Beasts", new String[] {"A place to kill ganodermic beasts to get your own ganodermic armour set! <br> You'll need 95 slayer to kill the beasts. <br><br>Information:<br> Ganodermic visor: 500 flakes<br> Ganodermic poncho: 5000 flakes<br>Ganodermic leggings: 1500 flakes. "}, 0, new WorldTile(4654, 5485, 0), false, -1, 3,false)),
            JADINKOS(15, new Teleport(2, new TeleportCategory(6, "Skilling"), "Jadinkos", new String[] {"A place to kill mutated jadinko babies, mutated jadinko guards and mutated jadinko males.<br><br>Information:<br> You need level 91 slayer to kill the mutated jadinko males. "}, 0, new WorldTile(3013, 9273, 0), false, -1, 3,false)),
            CHAOS_TUNNELS(15, new Teleport(3, new TeleportCategory(6, "Skilling"), "Chaos Tunnels", new String[] {"The Chaos Tunnels are a large dungeon network located in low-level Wilderness, north of Edgeville."}, 0, new WorldTile(3170, 5513, 0), false, -1, 3,false)),
            ANCIENT_CAVERNS(15, new Teleport(4, new TeleportCategory(6, "Skilling"), "Ancient Caverns", new String[] {"The Ancient Cavern is an area, which contains many high-level monsters, including a high level metal dragon, the mithril dragon."}, 0, new WorldTile(2512, 3515, 0), false, -1, 3,false)),
            DRAGON_DUNGEON(15, new Teleport(5, new TeleportCategory(6, "Skilling"), "Dragon Dungeon", new String[] {"A cavern where you can slay Green, blue and black dragons!"}, 0, new WorldTile(2722, 9774, 0), false, -1, 3,false)),
            TAVERLY_DUNGEON(15, new Teleport(6, new TeleportCategory(6, "Skilling"), "Taverly Dungeon", new String[] {"A cavern where there are many monsters, ranging from low to high combat levels and with the stronger ones located deeper in the dungeon. "}, 0, new WorldTile(2884, 9805, 0), false, -1, 3,false)),
            KURADALS_BROTHERS(15, new Teleport(7, new TeleportCategory(6, "Skilling"), "Kuradals Brothers", new String[] {"A teleport to deep wilderness where you can kill Kuradals brothers, Kurasal and Kurafal for some nice rewards!"}, 0, new WorldTile(3135, 3889, 0), true, 47, 3,false)),
            RUNE_ADDY_DRAGONS(15, new Teleport(8, new TeleportCategory(6, "Skilling"), "Rune & Addy Dragons", new String[] {"An isle where you can slay adamantite dragons and runite dragons"}, 0, new WorldTile(2131, 3856, 0), false, -1, 3,false)),
            STRYKEWYRMS(15, new Teleport(9, new TeleportCategory(6, "Skilling"), "Strykewyrms", new String[] {"A place to kill strykewyrms <br><br>Information:<br> you need at least a slayer level of 73 to fight this."}, 0, new WorldTile(2924, 4819, 0), false, -1, 3,false)),
            //JUNGLESTRYKEWYRMS(15, new Teleport(9, new TeleportCategory(6, "Skilling"), "Jungle Strykewyrms", new String[] {"A place to kill jungle strykewyrms <br><br>Information:<br> you need at least a slayer level of 73 to fight this."}, 0, new WorldTile(2461, 2898, 0), false, -1, 3,false)),
            //DESERTSTRYKEWYRMS(15, new Teleport(9, new TeleportCategory(6, "Skilling"), "Desert Strykewyrms", new String[] {"A place to kill desert strykewyrms <br><br>Information:<br> you need at least a slayer level of 77 to fight this."}, 0, new WorldTile(3376, 3158, 0), false, -1, 3,false)),
            //ICESTRYKEWYRMS(15, new Teleport(9, new TeleportCategory(6, "Skilling"), "Ice Strykewyrms", new String[] {"A place to kill ice strykewyrms<br><br>Information:<br> you need at least a slayer level of 93 to fight this."}, 0, new WorldTile(2378, 3891, 0), false, -1, 3,false)),
            SMOKE_DEVILS(15, new Teleport(10, new TeleportCategory(6, "Skilling"), "Smoke Devils", new String[] {"A cavern to kill smoke devils and the Thermonuclear smoke devil! <br><br>Information:<br> You need at least a slayer level of 93 to fight this monster."}, 0, new WorldTile(3662, 5770, 0), false, -1, 3,false)),
            LIZARDMAN_SHAMAN(15, new Teleport(11, new TeleportCategory(6, "Skilling"), "Lizardman Shaman", new String[] {"Lizardman shamans are giant reptilian humanoids that are stronger than their normal lizardmen and lizardmen brute counterparts.<br>They are often sought after for their dragon warhammer drops."}, 0, new WorldTile(1495, 3700, 0), false, -1, 3,false)),
            FREMENNIK_DUNGEON(15, new Teleport(12, new TeleportCategory(6, "Skilling"), "Fremennik Dungeon", new String[] {"A cave system found south-east of Rellekka, featuring several slayer monsters<br>cave crawlers, rockslugs, cockatrices, pyrefiends, basilisks, jellies, turoths, kurasks and aquanites can be found here.   "}, 0, new WorldTile(2804, 10001, 0), false, -1, 3,false)),
            CAVE_HORRORS(15, new Teleport(13, new TeleportCategory(6, "Skilling"), "Cave Horrors", new String[] {"A cave where you find cave horrors."}, 0, new WorldTile(3795, 9444, 0), false, -1, 3,false)),
            BRIMHAVEN_DUNGEON(15, new Teleport(14, new TeleportCategory(6, "Skilling"), "Brimhaven Dungeon", new String[] {"The brimhaven dungeon is often visited for its large variety of monsters.<br>wild dogs, moss giants, fire giants, bronze dragons, black demons , iron dragons and steel dragons can be found here."}, 0, new WorldTile(2718, 9481, 0), false, -1, 3,false)),
            CATACOMBS(15, new Teleport(15, new TeleportCategory(6, "Skilling"), "Catacombs of Kourend", new String[] {"The catacombs of kourend is a massive dungeon with lots of different slayer monsters.<br>hill giants, moss giants, fire giants, bloodvelds, nechryaels, abyssal demons, dark beasts, <br>lesser demons, greater demons, black demons, ghosts, jellies, dust devils, sand crabs,<br> dagganoths, ankous, banshees, aberrant spectres, hellhounds, skeletons,<br> black dragons, bronze dragons, iron dragons and steel dragons. "}, 0, new WorldTile(1666, 10049, 0), false, -1, 3,false)),
            WYVERN_CAVE(15, new Teleport(16, new TeleportCategory(6, "Skilling"), "Wyvern Cave", new String[] {"A cavern where you can kill spitting wyverns, taloned wyverns, long-tailed wyverns and ancient wyverns. <br><br>information:<br>You must have 66 slayer to access this cave!<br>you cannot attack these wyverns without either an elemental shield, dragonfire shield or ancient wyvern shield.    "}, 0, new WorldTile(3614, 10279, 0), false, -1, 3,false)),
            KARUULM_SLAYER(15, new Teleport(17, new TeleportCategory(6, "Skilling"), "Karuulm Slayer", new String[] {"The Karuulm Slayer Dungeon is a dungeon it contains a variety of monsters, as well as draconic creatures not found anywhere else.<br>sulphur lizards, wyrms and hydras can be found here.<br><br>Information:<br> You need at least a slayer level of 44 to fight sulphur lizards.<br>You need at least a slayer level of 62 to fight wyrms.<br>You need at least a slayer level of 95 to fight hydras."}, 0, new WorldTile(1312, 10189, 0), false, -1, 3,false)),
            GLACORS(15, new Teleport(18, new TeleportCategory(6, "Skilling"), "Glacors", new String[] {"Freezing cold cave where you can kill glacors for their boots.<br><br>Information:<br>You must have 50 slayer to access to this cave."}, 0, new WorldTile(4182, 5731, 0), false, -1, 3,false)),
            FROSTDRAG(15, new Teleport(19, new TeleportCategory(6, "Skilling"), "Frost Dragons", new String[] {"Freezing cold cave where you can kill frost dragons for their bones."}, 0, new WorldTile(1298, 4510, 0), false, -1, 3,false)),
       MINING(16, new Teleport(5, new TeleportCategory(4, "Skilling"), "Mining", new String[] {"Select an area you would like to train Mining."}, 0, null, false, -1, -1,false)),       
            MINING_GUILD(16, new Teleport(0, new TeleportCategory(6, "Skilling"), "Mining Guild", new String[] {"The perfect cave to find all the coal in the world!"}, 0, new WorldTile(3025, 9739, 0), false, -1, 3,false)),
            AL_KHARID(16, new Teleport(1, new TeleportCategory(6, "Skilling"), "Al Kharid", new String[] {"Ores in the al kharid desert, a good wy to start out your mining journey."}, 0, new WorldTile(3298, 3283, 0), false, -1, 3,false)),
            ESSENCE(16, new Teleport(2, new TeleportCategory(6, "Skilling"), "Essence Mine", new String[] {"The magical area where you can find and mine rune essence and pure essence.<br><br>Information:<br>Mining level 1-29 Rune essence<br>Mining level 30-99 Pure essence."}, 0, new WorldTile(2924, 4819, 0), false, -1, 3,false)),
            LIVINGROCK(16, new Teleport(3, new TeleportCategory(6, "Skilling"), "Living Rock Mine", new String[] {"A cave where you can find concentrated coal and concentrated gold depostits, living rock protectors, living rock strikers and living rock patriarch also a place to fish cavefish and rocktails. "}, 0, new WorldTile(3656, 5113, 0), false, -1, 3,false)),
            LAVA_FLOW(16, new Teleport(4, new TeleportCategory(6, "Skilling"), "Lava Flow", new String[] {"A place where you can semi-afk train your mining. <br><br>Information:<br>you need at least a mining level of 68 to mine this."}, 0, new WorldTile(2184, 5664, 0), false, -1, -1,false)),            
       THIEVING(17, new Teleport(6, new TeleportCategory(4, "Skilling"), "Thieving", new String[] {"Select an area you would like to train Thieving"}, 0, null, false, -1, -1,false)),       
            HOME_AREA(17, new Teleport(0, new TeleportCategory(6, "Skilling"), "Home Stalls", new String[] {"A place to steal goods from stalls and sell for profit."}, 0, new WorldTile(2858, 3336, 0), false, -1, 3,false)),
            ARDOUGNE(17, new Teleport(1, new TeleportCategory(6, "Skilling"), "Ardougne", new String[] {"A place to steal from stalls or pickpocket guards, knights of ardougne or paladins."}, 0, new WorldTile(2662, 3303, 0), false, -1, 3,false)),
       SUMMONING(18, new Teleport(7, new TeleportCategory(4, "Skilling"), "Summoning", new String[] {"Select an area you would like to train Summoning."}, 0, null, false, -1, -1,false)),       
            SUMMON(18, new Teleport(0, new TeleportCategory(6, "Skilling"), "Summoning Cave", new String[] {"A summoning obelisk to train your summoning on!"}, 0, new WorldTile(2333, 10015, 0), false, -1, 3,false)),
       HUNTER(19, new Teleport(8, new TeleportCategory(4, "Skilling"), "Hunter", new String[] {"Select an area you would like to train Hunter."}, 0, null, false, -1, -1,false)),       
            MAINHUNTER(19, new Teleport(0, new TeleportCategory(6, "Skilling"), "Main Hunter Area", new String[] {"Starter hunting location near feldip hills!"}, 0, new WorldTile(2525, 2915, 0), false, -1, 3,false)),
            FALCONRY(19, new Teleport(1, new TeleportCategory(6, "Skilling"), "Falconry", new String[] {"Place to hunt normal chinchompas.<br><br>Information:<br>you need at least a hunter level of 53 to catch this."}, 0, new WorldTile(2372, 3624, 0), false, -1, 3,false)),
            PURO(19, new Teleport(2, new TeleportCategory(6, "Skilling"), "Puro-Puro", new String[] {"Puro-Puro is the magical homeworld for imp-like creatures.<br><br>Information:<br>You need at least a hunter level of 17 to catch baby implings.<br>You need at least a hunter level of 22 to catch young implings.<br>You need at least a hunter level of 28 to catch gourmet implings.<br>You need at least a hunter level of 36 to catch earth implings.<br>You need at least a hunter level of 42 to catch essence implings.<br>You need at least a hunter level of 50 to catch eclectic implings.<br>You need at least a hunter level of 58 to catch nature implings.<br>You need at least a hunter level of 65 to catch magpie implings.<br>You need at least a hunter level of 74 to catch ninja implings.<br>You need at least a hunter level of 83 to catch dragon implings.<br>You need at least a hunter level of 89 to catch lucky implings.<br>"}, 0, new WorldTile(2591, 4319, 0), false, -1, 3,false)),
            BLACKCHIMCOMPAS(19, new Teleport(3, new TeleportCategory(6, "Skilling"), "Black Chinchompas", new String[] {"Place in level 33 wilderness to hunt black chinchompas.<br><br>Information:<br>you need at least a hunter level of 73 to catch this."}, 0, new WorldTile(3137, 3778, 0), true, 33, 3,false)),
       AGILITY(20, new Teleport(9, new TeleportCategory(4, "Skilling"), "Agility", new String[] {"Select an area you would like to train Agility."}, 0, null, false, -1, -1,false)),       
            GNOMEAGIL(20, new Teleport(0, new TeleportCategory(6, "Skilling"), "Gnome Agility", new String[] {"The perfect place to start your amazing agility journey!<br><br>Information:<br>Do this course from level 1 till level 35<br>Do this course from level 85 till level 90."}, 0, new WorldTile(2468, 3437, 0), false, -1, 3,false)),
            BARBOUTPOST(20, new Teleport(1, new TeleportCategory(6, "Skilling"), "Barbarian Outpost", new String[] {"An agility course ran by barbarians! <br><br>Information:<br>Do this course from level 35 till level 52.<br>Do this course from level 90 till level 99."}, 0, new WorldTile(2552, 3563, 0), false, -1, 3,false)),
       FISHING(21, new Teleport(10, new TeleportCategory(4, "Skilling"), "Fishing", new String[] {"Select an area you would like to train Fishing."}, 0, null, false, -1, -1,false)),       
            HOMEFISH(21, new Teleport(0, new TeleportCategory(6, "Skilling"), "Home Docks", new String[] {"Teleport to the fishing docks at home where you can catch fish starting from shrimps all the way to sharks!"}, 0, new WorldTile(2876, 3337, 0), false, -1, 3,false)),
            FISHGUILD(21, new Teleport(1, new TeleportCategory(6, "Skilling"), "Fishing Guild", new String[] {"Teleport to the fishing guild where you can catch fish starting from shrimps all the way to sharks!"}, 0, new WorldTile(2599, 3421, 0), false, -1, 3,false)),
            LRC(21, new Teleport(2, new TeleportCategory(6, "Skilling"), "Living Rock Caverns", new String[] {"Teleport to the Living Rock Cavern where you can fish cavefish and rocktails!"}, 0, new WorldTile(3656, 5113, 0), false, -1, 3,false)),
        RUNECRAFTING(22, new Teleport(11, new TeleportCategory(4, "Skilling"), "Runecrafting", new String[] {"Select an area you would like to train Runecrafting."}, 0, null, false, -1, -1,false)),       
            ABYSS(22, new Teleport(0, new TeleportCategory(6, "Skilling"), "Runecrafting Abyss", new String[] {"A dark place where you can find a quick teleport to every rune altar in game!"}, 0, new WorldTile(3042, 4844, 0), false, -1, 3,false)),
            ZMI_ALTAR(22, new Teleport(1, new TeleportCategory(6, "Skilling"), "ZMI Altar", new String[] {"The best place to train up your runecrafting!<br><br>Information:<br> You must've completed Rue's altar quest before accessing this altar.<br>This altar gives X2 base exp compaired to the normal altars."}, 0, new WorldTile(3305, 4809, 0), false, -1, 3,false)),
            RUNESPAN(22, new Teleport(2, new TeleportCategory(6, "Skilling"), "Runespan", new String[] {"A dimension where runic energies are much purer than on Gielinor. Players can siphon rune energy from creatures that roam the area, or from intermittent nodes."}, 0, new WorldTile(3105, 3163, 1), false, -1, 3,false)),
        SMITHING(23, new Teleport(12, new TeleportCategory(4, "Skilling"), "Smithing", new String[] {"Select an area you would like to train Smithing."}, 0, null, false, -1, -1,false)),       
            LAVASMITH(23, new Teleport(0, new TeleportCategory(6, "Skilling"), "Lava Smithing Area", new String[] {"A dark cave where you can smelt and smith your ores!<br>There is a coal storage available here to make your bar smelting easier."}, 0, new WorldTile(1751, 5289, 1), false, -1, 3,false)),
        CONSTRUCTION(24, new Teleport(13, new TeleportCategory(4, "Skilling"), "Construction", new String[] {"Select an area you would like to train Construction."}, 0, null, false, -1, -1,false)),       
            YANILLE(24, new Teleport(0, new TeleportCategory(6, "Skilling"), "Yanille", new String[] {"Your 'new' home! the place to buy your house, train your construction up and even buy construction supplies!"}, 0, new WorldTile(2542, 3095, 0), false, -1, 3,false)),
        CRAFTING(25, new Teleport(14, new TeleportCategory(4, "Skilling"), "Crafting", new String[] {"Select an area you would like to train Crafting."}, 0, null, false, -1, -1,false)),       
            ORB(25, new Teleport(0, new TeleportCategory(6, "Skilling"), "Orb Charging", new String[] {"An isle to charge your unpowerd orbs, you can find the obelisk of air, obelisk of water, obelisk of earth and obelisk of fire here!<br><br>Information:<br>You must have 3 cosmic rune and 30 of elemental runes to change a orb."}, 0, new WorldTile(2840, 3420, 0), false, -1, 3,false)),

            
            //AREAS
        DONATOR(13, new Teleport(0, new TeleportCategory(5, "Areas"), "Donator Zones", new String[] {"Exclusive zones for players who support the game."}, 0, null, false, -1,-1,false)),
            DZ1(13, new Teleport(0, new TeleportCategory(7, "Areas"), "Regular", new String[] {"Zone for <img=8><col=046063>Regular</col> donators. <br> Zone benefits: <br> <col=046063>Buyable Overload Potions <br> <col=046063>Donator shops <br> <col=046063>+ MORE!"}, 0, new WorldTile(3363, 9632, 0), false, -1,-1,false)),
            DZ2(13, new Teleport(1, new TeleportCategory(7, "Areas"), "Extreme", new String[] {"Zone for <img=9><col=780904>Extreme</col> donators. <br> Zone benefits: <br> <col=780904>Dream trees for Overkill Potions <br> <col=780904>+ MORE!"}, 0, new WorldTile(1898, 5355, 2), false, -1,-1,false)),
            DZ3(13, new Teleport(2, new TeleportCategory(7, "Areas"), "Legendary", new String[] {"Zone for <img=13><col=d68b09>Legendary</col> donators. <br> Zone benefits: <br> <col=d68b09>10% XP Buff <br> <col=d68b09>Donor only Slayer Master <br> <col=d68b09>+ MORE!"}, 0, new WorldTile(1832, 5088, 2), false, -1,-1,false)),
            DZ4(13, new Teleport(3, new TeleportCategory(7, "Areas"), "VIP", new String[] {"Zone for <img=14><col=ba09a3>VIP</col> donators. <br> Zone benefits: <col=ff00ff><br> <col=ba09a3>20% XP Buff <br> <col=ba09a3>VIP only boss <br> <col=ba09a3>+ MORE!"}, 0, new WorldTile(2595, 5581, 0), false, -1,-1,false)),
            DZ5(13, new Teleport(4, new TeleportCategory(7, "Areas"), "Sponsor", new String[] {"Zone for <img=19><col=E6CC07>Sponsor</col> donators. <br> Zone benefits: <br> <col=E6CC07>40% XP Buff <br> <col=E6CC07>Easy skilling <br> <col=E6CC07>+ MORE!"}, 0, new WorldTile(3416, 5275, 0), false, -1,-1,false)),
            
        COMMUNITY_EVENTS(14, new Teleport(1, new TeleportCategory(5, "Areas"), "Community Areas", new String[] {"Please select which world event you would like to participate in."}, 0, null, false, -1,-1,false)),
            GAMBLE(14, new Teleport(0, new TeleportCategory(7, "Areas"), "Gamble Zone", new String[] {"A peaceful place to gamble your money/items."}, 0, new WorldTile(2854, 2576,0), false, -1,-1,false)),
            PARTY_DEMON(14, new Teleport(1, new TeleportCategory(7, "Areas"), "Party Demon", new String[] {"A worldevent boss that spawns twice a day at set times.<br><br>Information:<br>The party demon spawns daily at 07:00 AM server time and 06:00 PM server time<br>Only players with a total level of 1500 can loot the chest!"}, 0, new WorldTile(3249,9867, 0), false, -1,-1,false)),
            ASSASSIN(14, new Teleport(2, new TeleportCategory(7, "Areas"), "Assassin", new String[] {"A hard world event boss that spawns four times a day at set times.<br><br>Information:<br>The assassin spawns daily at 06:00 AM server time, 12:00 PM server time, 18:00 PM server time and 12:00 AM server time."}, 0, new WorldTile(3515, 9837, 0), false, -1,-1,false)),
            INGENUITY(14, new Teleport(3, new TeleportCategory(7, "Areas"), "Ingenuity", new String[] {"A skilling boss where you have to Mine, woodcut, fish, firemake to 'kill' this boss. <br><br>Information:<br>Only players with a total level of 1500 can loot the chest!"}, 0, new WorldTile(2591, 3909, 0), false, -1,-1,false)),
            
        PRESTIGE_ZONE(15, new Teleport(2, new TeleportCategory(5, "Areas"), "Prestige Zones", new String[] {"A special place for the most elite players!"}, 0, null, false, -1,-1,false)),
            PRESTIGE1(15, new Teleport(0, new TeleportCategory(7, "Areas"), "Prestige Zone", new String[] {"A magical place where you can woodcut maple, yew and magic trees. mine gold ore, coal ore, adamantite ore and runite ore.<br>A place to smith your ores, train your firemaking and even a special prestige shop. "}, 0, new WorldTile(1382, 3816, 0), false, -1,-1,false)),
            
        CITIES(16, new Teleport(3, new TeleportCategory(5, "Areas"), "Cities", new String[] {"Please select which city you would like to visit."}, 0, null, false, -1,-1,false)),
            SHILOVILLAGE(16, new Teleport(0, new TeleportCategory(7, "Areas"), "Shilo Village", new String[] {"Shilo Village is a village on Karamja."}, 0, new WorldTile(2825, 2999, 0), false, -1,-1,false)),
            LUMBRIDGE(16, new Teleport(1, new TeleportCategory(7, "Areas"), "Lumbridge", new String[] {"Its main features include Lumbridge Castle, where players can start several quests, and where there is also a bank to deposit/withdraw items"}, 0, new WorldTile(3222, 3219, 0), false, -1,-1,false)),
            VARROCK(16, new Teleport(2, new TeleportCategory(7, "Areas"), "Varrock", new String[] {"Varrock is the capital of the kingdom of Misthalin."}, 0, new WorldTile(3212, 3422, 0), false, -1,-1,false)),
            EDGEVILLE(16, new Teleport(3, new TeleportCategory(7, "Areas"), "Edgeville", new String[] {"Edgeville is a small town located at the border of the Wilderness available to free players."}, 0, new WorldTile(3094, 3502, 0), false, -1,-1,false)),
            FALADOR(16, new Teleport(4, new TeleportCategory(7, "Areas"), "Falador", new String[] {"Falador is the capital city of The Kingdom of Asgarnia. It is one of the largest and most major cities."}, 0, new WorldTile(2965, 3386, 0), false, -1,-1,false)),
            SEERS_VILLAGE(16, new Teleport(5, new TeleportCategory(7, "Areas"), "Seers Village", new String[] {"Seers' Village is a small settlement to the west of Camelot. The city of Ardougne is to the south, and Rellekka and Sinclair Mansion are to the north"}, 0, new WorldTile(2725, 3491, 0), false, -1,-1,false)),
            ARDOUGNE2(16, new Teleport(6, new TeleportCategory(7, "Areas"), "Ardougne", new String[] {"Ardougne is the capital of the Kingdom of Kandarin."}, 0, new WorldTile(2662, 3305, 0), false, -1,-1,false)),
            YANNILE(16, new Teleport(7, new TeleportCategory(7, "Areas"), "Yannile", new String[] {"Yanille is a city that lies to the south of Ardougne."}, 0, new WorldTile(2605, 3093, 0), false, -1,-1,false)),
            KELDAGRIM(16, new Teleport(8, new TeleportCategory(7, "Areas"), "Keldagrim", new String[] {"Keldagrim is the city of the dwarves"}, 0, new WorldTile(2845, 10210, 0), false, -1,-1,false)),
            DORGESHKAAN(16, new Teleport(9, new TeleportCategory(7, "Areas"), "Dorgesh-Kaan", new String[] {"The Republic of Dorgesh-Kaan is the capital city of the Dorgeshuun cave goblin tribe."}, 0, new WorldTile(2720, 5351, 0), false, -1,-1,false)),
            LLETYA(16, new Teleport(10, new TeleportCategory(7, "Areas"), "Lletya", new String[] {"Lletya is an elven village in Tirannwn."}, 0, new WorldTile(2341, 3171, 0), false, -1,-1,false)),
            ECTERIA(16, new Teleport(11, new TeleportCategory(7, "Areas"), "Etceteria", new String[] {"Etceteria is a city located on an island east of the kingdom of Miscellania."}, 0, new WorldTile(2614, 3894, 0), false, -1,-1,false)),
            DAEMONHEIM(16, new Teleport(12, new TeleportCategory(7, "Areas"), "Daemonheim", new String[] {"Daemonheim is a huge dungeon created by the Mahjarrat Bilrach."}, 0, new WorldTile(3450, 3718, 0), false, -1,-1,false)),
            CANIFIS(16, new Teleport(13, new TeleportCategory(7, "Areas"), "Canifis", new String[] {"Canifis is a village that lies to the east of Paterdomus, across the River Salve, in Morytania."}, 0, new WorldTile(3496, 3489, 0), false, -1,-1,false)),
            TZHAARAREA(16, new Teleport(14, new TeleportCategory(7, "Areas"), "Tzhaar area", new String[] {"The TzHaar City is a city located underneath the volcano on Karamja. It is home to the TzHaar, a golem-like humanoid race."}, 0, new WorldTile(4651, 5151, 0), false, -1,-1,false)),
            BURTHROPE(16, new Teleport(15, new TeleportCategory(7, "Areas"), "Burthrope", new String[] {"Burthorpe is a military principality north-west of Falador and north of Taverley."}, 0, new WorldTile(2889, 3528, 0), false, -1,-1,false)),
            ALKHARID(16, new Teleport(16, new TeleportCategory(7, "Areas"), "Al-Kharid", new String[] {"Al Kharid is a city on the northern border of the Kharidian Desert."}, 0, new WorldTile(3275, 3166, 0), false, -1,-1,false)),
            DRAYNOR(16, new Teleport(17, new TeleportCategory(7, "Areas"), "Draynor village", new String[] {"Draynor Village is a small village located between Falador and Lumbridge."}, 0, new WorldTile(3079, 3250, 0), false, -1,-1,false)),
            ZANARIS(16, new Teleport(18, new TeleportCategory(7, "Areas"), "Zanaris", new String[] {"The Kingdom of Zanaris is Gielinor's moon. It is a strange plane, rumoured to be the nexus of all planes."}, 0, new WorldTile(2386, 4458, 0), false, -1,-1,false)),
            DARKMEYER(16, new Teleport(19, new TeleportCategory(7, "Areas"), "Darkmeyer", new String[] {"Darkmeyer is the capital of the Sanguinesti region and is inhabited by vampyres."}, 0, new WorldTile(3613, 3371, 0), false, -1,-1,false)),
            
         PVP(17, new Teleport(4, new TeleportCategory(5, "Areas"), "PVP", new String[] {"Please select which PVP zone you would like to teleport to."}, 0, null, false, -1,-1,false)),
            MAGE_BANK(17, new Teleport(0, new TeleportCategory(7, "Areas"), "Mage Bank", new String[] {"A teleport to the mage bank, the place people use to get to the wilderness agility course or hybrid pk!"}, 0, new WorldTile(2538, 4715, 0), true, 55,-1,false)),
            CLAN_WARS2(17, new Teleport(1, new TeleportCategory(7, "Areas"), "Clan Wars", new String[] {"A place for players to engage in player-versus-player combat against one another"}, 0, new WorldTile(2992, 9678, 0), false, -1, -1,false)),
            MULTI_AREA(17, new Teleport(2, new TeleportCategory(7, "Areas"), "Multi Area", new String[] {"A place in level 12 wilderness which is a multi area!"}, 0, new WorldTile(3240, 3611, 0), true, 12,-1,false)),
            WESTS(17, new Teleport(3, new TeleportCategory(7, "Areas"), "Wests", new String[] {"A place in level 10 wilderness just south from the dark warriors' fortress on the west side on the wilderness.<br>You can find three green dragons when you run north."}, 0, new WorldTile(2984, 3596, 0), true, 10,-1,false)),
            EASTS(17, new Teleport(4, new TeleportCategory(7, "Areas"), "Easts", new String[] {"A place in level 18 wilderness east from the graveyard of shadows, on the east side of the wilderness.<br> You can find ten green dragons when you run north."}, 0, new WorldTile(3360, 3658, 0), true, 18,-1,false)),
            REVENANTS(17, new Teleport(5, new TeleportCategory(7, "Areas"), "Revenants", new String[] {"Wipe out the restless ghosts sweeping around the revenant caves to receive a rare chance of weapons and resources!<br>You can find green dragons, Greater demons and hellhounds on your way to the revenants.<br> The revenants are found in level 27-32 wilderness."}, 0, new WorldTile(3081, 10057, 0), true, 18,-1,false)),
            
      
        
        
        ;
        Store(final int id, final Teleport teleport) {
            this.id = id;
            this.teleport = teleport;
        }

        private int id;

        public int getId() {
            return id;
        }

        public Teleport getTeleport() {
            return teleport;
        }

        private Teleport teleport;
    }
    
    
    //        ARMADYL(1, new Teleport(1, new TeleportCategory(0, "Bosses"), "Armadyl", "Armadyl (GWD), is the avian god of justice.", 1000000, new WorldTile(839, 5288, 2), false, -1, 105)),
//ZAMORAK(2, new Teleport(2, new TeleportCategory(0, "Bosses"), "Zamorak", " Zamorak (GWD), was once a Mahjarrat who sought to be heir of Zaros.", 1000000, new WorldTile(2922, 5347, 2), false, -1, 105)),
//SARADOMIN(3, new Teleport(3, new TeleportCategory(0, "Bosses"), "Saradomin", "Saradomin (GWD), is the god of order and wisdom.", 1000000, new WorldTile(2930, 5298, 1), false, -1, 105)),
//CORPOREAL_BEAST(4, new Teleport(4, new TeleportCategory(0, "Bosses"), "Corporeal Beast", "The Corporeal Beast is the physical incarnation of the Spirit Beast, and is a boss monster.", 1000000, new WorldTile(100,100,0), false, -1, 100)),
//DKS(5, new Teleport(5, new TeleportCategory(0, "Bosses"), "Dagannoth Kings", "The Dagannoth Kings are a group of three dagannoths living deep in the cave on Waterbirth Island.", 200000, new WorldTile(1912, 4367, 0), false, -1, 100)),
//GIANT_MOLE(6, new Teleport(6, new TeleportCategory(0, "Bosses"), "Giant Mole", "The giant mole (Talpidae wysonian) is a female mole found in the Falador Mole Lair, just under Falador Park.", 50000, new WorldTile(3003, 3377, 0), false, -1, 100)),
//TORMENTED_DEMON(7, new Teleport(7, new TeleportCategory(0, "Bosses"), "Tormented Demons", "Tormented demons are massive demons summoned and controlled by the Mahjarrat Lucien.", 500000, new WorldTile(2555, 5743, 0), false, -1, 110)),
//NEX(8, new Teleport(8, new TeleportCategory(0, "Bosses"), "Nex", "(GWD) Nex is a powerful Zarosian general.", 1000000, new WorldTile(2967, 4383, 2), false, -1, 126)),
//CALLISTO(9, new Teleport(9, new TeleportCategory(0, "Bosses"), "Callisto", "Callisto is an enormous bear that resides south of the Demonic Ruins.", 100000, new WorldTile(2904, 5204, 0), true, 38, 100)),
//VENENATIS(10, new Teleport(10, new TeleportCategory(0, "Bosses"), "Venenatis", "Venenatis is a large poison spider that resides east of the Bone Yard.", 100000, new WorldTile(3280, 3823, 0), true, 31, 100)),
//SCORPIA(11, new Teleport(11, new TeleportCategory(0, "Bosses"), "Scorpia", "Scorpia is a large female scorpion that resides in a cave beneath the Scorpion Pit.", 100000, new WorldTile(3336, 3761, 0), true, 54, 100)),
////CITIES

//VARROCK(15, new Teleport(1, new TeleportCategory(2, "Cities"), "Varrock", "Varrock is the capital of the kingdom of Misthalin.", 0, new WorldTile(3212, 3422, 0), false, -1,-1)),
//EDGEVILLE(16, new Teleport(2, new TeleportCategory(2, "Cities"), "Edgeville", "Edgeville is a small town located at the border of the Wilderness available to free players.", 0, new WorldTile(3094, 3502, 0), false, -1,-1)),
//FALADOR(17, new Teleport(3, new TeleportCategory(2, "Cities"), "Falador", "Falador is the capital city of The Kingdom of Asgarnia. It is one of the largest and most major cities.", 0, new WorldTile(2965, 3386, 0), false, -1,-1)),
//SEERS_VILLAGE(18, new Teleport(4, new TeleportCategory(2, "Cities"), "Seers Village", "Seers' Village is a small settlement to the west of Camelot. The city of Ardougne is to the south, and Rellekka and Sinclair Mansion are to the north", 0, new WorldTile(2725, 3491, 0), false, -1, -1)),
//ARDOUGNE(19, new Teleport(5, new TeleportCategory(2, "Cities"), "Ardougne", "Ardougne is the capital of the Kingdom of Kandarin.", 0, new WorldTile(2662, 3305, 0), false, -1,-1)),
//YANNILE(20, new Teleport(6, new TeleportCategory(2, "Cities"), "Yannile", "Yanille is a city that lies to the south of Ardougne.", 0, new WorldTile(2605, 3093, 0), false, -1,-1)),
//KELDAGRIM(21, new Teleport(7, new TeleportCategory(2, "Cities"), "Keldagrim", "Keldagrim is the city of the dwarves", 0, new WorldTile(2845, 10210, 0), false, -1,-1)),
//DORGESHKAAN(22, new Teleport(8, new TeleportCategory(2, "Cities"), "Dorgesh-Kaan", "The Republic of Dorgesh-Kaan is the capital city of the Dorgeshuun cave goblin tribe.", 0, new WorldTile(2720, 5351, 0), false, -1,-1)),
//LLETYA(23, new Teleport(9, new TeleportCategory(2, "Cities"), "Lletya", "Lletya is an elven village in Tirannwn.", 0, new WorldTile(2341, 3171, 0), false, -1,-1)),
//ECTERIA(24, new Teleport(10, new TeleportCategory(2, "Cities"), "Etceteria", "Etceteria is a city located on an island east of the kingdom of Miscellania.", 0, new WorldTile(2614, 3894, 0), false, -1,-1)),
//DAEMONHEIM(25, new Teleport(11, new TeleportCategory(2, "Cities"), "Daemonheim", "Daemonheim is a huge dungeon created by the Mahjarrat Bilrach.", 0, new WorldTile(3450, 3718, 0), false, -1,-1)),
//CANIFIS(26, new Teleport(12, new TeleportCategory(2, "Cities"), "Canifis", "Canifis is a village that lies to the east of Paterdomus, across the River Salve, in Morytania.", 0, new WorldTile(3496, 3489, 0), false, -1,-1)),
//TZHAARAREA(27, new Teleport(13, new TeleportCategory(2, "Cities"), "Tzhaar area", "The TzHaar City is a city located underneath the volcano on Karamja. It is home to the TzHaar, a golem-like humanoid race.", 0, new WorldTile(4651, 5151, 0), false, -1,-1)),
//BURTHROPE(28, new Teleport(14, new TeleportCategory(2, "Cities"), "Burthrope", "Burthorpe is a military principality north-west of Falador and north of Taverley.", 0, new WorldTile(2889, 3528, 0), false, -1,-1)),
//ALKHARID(29, new Teleport(15, new TeleportCategory(2, "Cities"), "Al-Kharid", "Al Kharid is a city on the northern border of the Kharidian Desert.", 0, new WorldTile(3275, 3166, 0), false, -1,-1)),
//DRAYNOR(30, new Teleport(16, new TeleportCategory(2, "Cities"), "Draynor village", "Draynor Village is a small village located between Falador and Lumbridge.", 0, new WorldTile(3079, 3250, 0), false, -1,-1)),
//ZANARIS(31, new Teleport(17, new TeleportCategory(2, "Cities"), "Zanaris", "The Kingdom of Zanaris is Gielinor's moon. It is a strange plane, rumoured to be the nexus of all planes.", 0, new WorldTile(2386, 4458, 0), false, -1,-1)),
//SHILLO(32, new Teleport(18, new TeleportCategory(2, "Cities"), "Shillo Village", "Shilo Village is a village on Karamja.", 0, new WorldTile(2849, 2958, 0), false, -1,-1)),
//DARKMEYER(33, new Teleport(19, new TeleportCategory(2, "Cities"), "Darkmeyer", "Darkmeyer is the capital of the Sanguinesti region and is inhabited by vampyres.", 0, new WorldTile(3613, 3371, 0), false, -1,-1)),
////MINI-GAMES

//BARROWS(13, new Teleport(1, new TeleportCategory(1, "Minigames"), "Barrows", "The Barrows is an area-based combat minigame. It involves defeating the six Barrows brothers.", 100000, new WorldTile(3565, 3306, 0), false, -1, 95)),
//FIGHT_PITS(34, new Teleport(2, new TeleportCategory(1, "Minigames"), "Fight Pits", "The TzHaar Fight Pit is a PVP minigame located in TzHaar City.", 0, new WorldTile(4602, 5062, 0), false, -1, 100)),
//FIGHT_CAVES(35, new Teleport(3, new TeleportCategory(1, "Minigames"), "Fight Caves", "The TzHaar Fight Cave is a combat minigame located in TzHaar City.", 0, new WorldTile(4615, 5129, 0), false, -1, 110)),
//FIGHT_KILN(36, new Teleport(4, new TeleportCategory(1, "Minigames"), "Fight Kiln", "The Fight Kiln is a combat minigame wherein waves of TokHaar are fought for the sole sake of combat.", 0, new WorldTile(4743, 5170, 0), false, -1, 138)),
//PURO_PURO(37, new Teleport(5, new TeleportCategory(1, "Minigames"), "Puro-Puro", "Puro-Puro is a magical world, separate from Gielinor, and is the main location for the Impetuous Impulses minigame.", 0, new WorldTile(2428, 4441, 0), false, -1, 3)),
//CLAN_WARS(38, new Teleport(6, new TeleportCategory(1, "Minigames"), "Clan Wars", "Clan Wars is a minigame available to both free players and members located in the Gamers' Grotto.", 0, new WorldTile(2993, 9680, 0), false, -1, 3)),
//RUNESPAN(39, new Teleport(7, new TeleportCategory(1, "Minigames"), "Runespan", "The Runespan is a dimension where runic energies are much purer than on Gielinor.", 0, new WorldTile(3106, 3160, 0), false, -1, 3)),
//SORCERES_GARDEN(40, new Teleport(8, new TeleportCategory(1, "Minigames"), "Sorceres Garden", "The Sorceress's Garden, often abbreviated SG, is a Thieving/Farming minigame located in Al Kharid.", 0, new WorldTile(3323, 3139, 0), false, -1, 3)),
//DUNGEONEERING(41, new Teleport(9, new TeleportCategory(1, "Minigames"), "Dungeoneering", "Dungeoneering is a support skill that consists of exploring the dungeons of Gielinor.", 0, new WorldTile(3449, 3699, 0), false, -1, 80)),
//PEST_CONTROL(42, new Teleport(10, new TeleportCategory(1, "Minigames"), "Pest Control", "Pest Control is a co-operative combat-based minigame.", 0, new WorldTile(2659, 2676, 0), false, -1, 70)),
//WARRIOR_GUILD(43, new Teleport(11, new TeleportCategory(1, "Minigames"), "Warrior Guild", "The Warriors' Guild is a guild for warriors located in west Burthorpe.", 0, new WorldTile(2844, 3536, 2), false, -1, 80)),
//GAMBLING_AREA(44, new Teleport(12, new TeleportCategory(1, "Minigames"), "Gambling Area", "If you like to bet this is the right place!", 0, new WorldTile(2402, 2831, 0), false, -1, 3)),
////Monsters

//GOBLINS(46, new Teleport(1, new TeleportCategory(3, "Monsters"), "Goblins", "", 0, new WorldTile(2956, 3501, 0), false, -1, 3)),
//ROCK_CRABS(47, new Teleport(2, new TeleportCategory(3, "Monsters"), "Rock Crabs", "", 0, new WorldTile(2674, 3710, 0), false, -1, 3)),
//EXPERIMENTS(48, new Teleport(3, new TeleportCategory(3, "Monsters"), "Experiments", "", 0, new WorldTile(3555, 9947, 0), false, -1, 30)),
//YAKS(49, new Teleport(4, new TeleportCategory(3, "Monsters"), "Yaks", "" ,0, new WorldTile(2321, 3803, 0), false, -1, 40)),
//WOLFS(50, new Teleport(5, new TeleportCategory(3, "Monsters"), "Wolfs", "", 0, new WorldTile(2845, 3488, 0), false, -1, 50)),
//OGRES(51, new Teleport(6, new TeleportCategory(3, "Monsters"), "Ogres", "", 0, new WorldTile(2506, 3108, 0), false, -1, 60)),
//KARAMJA_CRANDOR(52, new Teleport(7, new TeleportCategory(3, "Monsters"), "Karamja & Crandor", "", 0, new WorldTile(2861, 9570, 0), false, -1, 70)),
//TAVERLEY_DUNGEON(53, new Teleport(8, new TeleportCategory(3, "Monsters"), "Taverley Dungeon", "", 0, new WorldTile(2886, 3395, 0), false, -1, 70)),
//BRIMHAVEN_DUNGEON(54, new Teleport(9, new TeleportCategory(3, "Monsters"), "Brimhaven Dungeon", "", 0, new WorldTile(2686, 9564, 0), false, -1, 70)),
//ANCIENT_CAVE(55, new Teleport(10, new TeleportCategory(3, "Monsters"), "Ancient Cave", "", 0, new WorldTile(2511, 3516, 0), false, -1, 70)),
//DAGGANOTH_CAVE(56, new Teleport(11, new TeleportCategory(3, "Monsters"), "Dagganoth Cave", "", 0, new WorldTile(2509, 3642, 0), false, -1, 70)),
//FREMENNIK_SLAYER_DUNGEON(57, new Teleport(12, new TeleportCategory(3, "Monsters"), "Fremennik Slayer Dungeon", "", 0, new WorldTile(2794, 3615, 0), false, -1, 70)),
//MOSLE_HARMLESS_DUNGEON(58, new Teleport(13, new TeleportCategory(3, "Monsters"), "Mos'le Harmless Dungeon", "", 0, new WorldTile(3751, 2973, 0), false, -1, 70)),
//BRINE_RAT_CAVE(59, new Teleport(14, new TeleportCategory(3, "Monsters"), "Brine Rat Cave", "", 0, new WorldTile(2748, 3733, 0), false, -1, 70)),
//ASGARNIA_ICE_DUNGEON(60, new Teleport(15, new TeleportCategory(3, "Monsters"), "Asgarnia Ice Dungeon", "", 0, new WorldTile(3034, 9583, 0), false, -1, 70)),
//GROTWORM_LAIR(61, new Teleport(16, new TeleportCategory(3, "Monsters"), "Grotworm Lair (QBD)", "", 0, new WorldTile(1206, 6506, 0), false, -1, 100)),
//LIVING_ROCK_CAVE(62, new Teleport(17, new TeleportCategory(3, "Monsters"), "Living Rock Cave", "", 0, new WorldTile(3017, 9832, 0), false, -1, 100)),
//KALPHITE_HIVE(63, new Teleport(18, new TeleportCategory(3, "Monsters"), "Kalphite Hive", "", 0, new WorldTile(3228, 3106, 0), false, -1, 100)),
//SLAYER_TOWER(64, new Teleport(19, new TeleportCategory(3, "Monsters"), "Slayer Tower", "", 0, new WorldTile(3429, 3523, 0), false, -1, 60)),
//JADINKOS_LAIR(65, new Teleport(20, new TeleportCategory(3, "Monsters"), "Jadinkos Lair", "", 0, new WorldTile(2946, 2953, 0), false, -1, 100)),
//JUNGLE_STRYKEWYRMS(66, new Teleport(21, new TeleportCategory(3, "Monsters"), "Jungle Strykewyrms", "", 0, new WorldTile(2450, 2898, 0), false, -1, 100)),
//DESERT_STRYKEWYRMS(67, new Teleport(22, new TeleportCategory(3, "Monsters"), "Desert Strykewyrms", "", 0, new WorldTile(3381, 3162, 0), false, -1, 100)),
//ICE_STRYKEWYRMS(68, new Teleport(23, new TeleportCategory(3, "Monsters"), "Ice Strykewyrms", "", 0, new WorldTile(3508, 5516, 0), false, -1, 100)),
//GANODERMIC_BEASTS_CAVE(69, new Teleport(24, new TeleportCategory(3, "Monsters"), "Ganodermic Beasts Cave", "", 0, new WorldTile(4723, 5467, 0), false, -1, 100)),
//GLACORS_CAVE(70, new Teleport(25, new TeleportCategory(3, "Monsters"), "Glacors Cave", "", 0, new WorldTile(4185, 5734, 0), false, -1, 100)),
////Skilling

//FISHING_GUILD(72, new Teleport(1, new TeleportCategory(4, "Skilling"), "Fishing Guild", "Recommended 1-99.", 0, new WorldTile(2595, 3414, 0), false, -1, 3)),
//GNOME_AGILITY(73, new Teleport(2, new TeleportCategory(4, "Skilling"), "Gnome Stronghold Agility", "Recommended 1-50.", 0, new WorldTile(2468, 3438, 0), false, -1, 3)),
//BARBARIAN_AGILITY(74, new Teleport(3, new TeleportCategory(4, "Skilling"), "Barbarian Outpost Agility", "Recommended 50-99.", 0, new WorldTile(2552, 3563, 0), false, -1, 3)),
//AIR_ALTAR(75, new Teleport(4, new TeleportCategory(4, "Skilling"), "Air Altar", "Requires level 1 in RC.", 0, new WorldTile(3133, 3405, 0), false, -1, 3)),
//WATER_ALTAR(76, new Teleport(5, new TeleportCategory(4, "Skilling"), "Waster Altar", "Requires level 2 in RC.", 0, new WorldTile(3190, 3160, 0), false, -1, 3)),
//EARTH_ALTAR(77, new Teleport(6, new TeleportCategory(4, "Skilling"), "Earth Altar", "Requires level 9 in RC.", 0, new WorldTile(3303, 3464, 0), false, -1, 3)),
//FIRE_ALTAR(78, new Teleport(7, new TeleportCategory(4, "Skilling"), "Fire Altar", "Requires level 14 in RC.", 0, new WorldTile(3318, 3261, 0), false, -1, 3)),
//ASTRAL_ALTAR(79, new Teleport(8, new TeleportCategory(4, "Skilling"), "Astral Altar", "Requires level 40 in RC.", 0, new WorldTile(2152, 3860, 0), false, -1, 3)),
//DEATH_ALTAR(80, new Teleport(9, new TeleportCategory(4, "Skilling"), "Death Alatar", "Requires level 65 in RC.", 0, new WorldTile(1863, 4639, 0), false, -1, 3)),
//BLOOD_ALTAR(81, new Teleport(10, new TeleportCategory(4, "Skilling"), "Blood Altar", "Requires level 77 in RC.", 0, new WorldTile(3563, 9773, 0), false, -1, 3)),
//PURE_ESSENCE(82, new Teleport(11, new TeleportCategory(4, "Skilling"), "Pure Essence", "", 0, new WorldTile(2910, 4831, 0), false, -1, 3)),
//HUNTER_STARTER(83, new Teleport(12, new TeleportCategory(4, "Skilling"), "Hunter Starter", "Start your adventure in hunter.", 0, new WorldTile(2606, 2923, 0), false, -1, 3)),

}
